// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/orchestrator.proto

package orchestrator

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubmitJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaxRetries    int32                  `protobuf:"varint,1,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitJobRequest) Reset() {
	*x = SubmitJobRequest{}
	mi := &file_proto_orchestrator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitJobRequest) ProtoMessage() {}

func (x *SubmitJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitJobRequest.ProtoReflect.Descriptor instead.
func (*SubmitJobRequest) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitJobRequest) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

type SubmitJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         int32                  `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitJobResponse) Reset() {
	*x = SubmitJobResponse{}
	mi := &file_proto_orchestrator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitJobResponse) ProtoMessage() {}

func (x *SubmitJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitJobResponse.ProtoReflect.Descriptor instead.
func (*SubmitJobResponse) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitJobResponse) GetJobId() int32 {
	if x != nil {
		return x.JobId
	}
	return 0
}

type GetJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         int32                  `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobRequest) Reset() {
	*x = GetJobRequest{}
	mi := &file_proto_orchestrator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobRequest) ProtoMessage() {}

func (x *GetJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobRequest.ProtoReflect.Descriptor instead.
func (*GetJobRequest) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_proto_rawDescGZIP(), []int{2}
}

func (x *GetJobRequest) GetJobId() int32 {
	if x != nil {
		return x.JobId
	}
	return 0
}

type GetJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         int32                  `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	RetryCount    int32                  `protobuf:"varint,3,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	MaxRetries    int32                  `protobuf:"varint,4,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobResponse) Reset() {
	*x = GetJobResponse{}
	mi := &file_proto_orchestrator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobResponse) ProtoMessage() {}

func (x *GetJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobResponse.ProtoReflect.Descriptor instead.
func (*GetJobResponse) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_proto_rawDescGZIP(), []int{3}
}

func (x *GetJobResponse) GetJobId() int32 {
	if x != nil {
		return x.JobId
	}
	return 0
}

func (x *GetJobResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetJobResponse) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *GetJobResponse) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

var File_proto_orchestrator_proto protoreflect.FileDescriptor

const file_proto_orchestrator_proto_rawDesc = "" +
	"\n" +
	"\x18proto/orchestrator.proto\x12\forchestrator\"3\n" +
	"\x10SubmitJobRequest\x12\x1f\n" +
	"\vmax_retries\x18\x01 \x01(\x05R\n" +
	"maxRetries\"*\n" +
	"\x11SubmitJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\x05R\x05jobId\"&\n" +
	"\rGetJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\x05R\x05jobId\"\x81\x01\n" +
	"\x0eGetJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\x05R\x05jobId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1f\n" +
	"\vretry_count\x18\x03 \x01(\x05R\n" +
	"retryCount\x12\x1f\n" +
	"\vmax_retries\x18\x04 \x01(\x05R\n" +
	"maxRetries2\xa8\x01\n" +
	"\x13OrchestratorService\x12L\n" +
	"\tSubmitJob\x12\x1e.orchestrator.SubmitJobRequest\x1a\x1f.orchestrator.SubmitJobResponse\x12C\n" +
	"\x06GetJob\x12\x1b.orchestrator.GetJobRequest\x1a\x1c.orchestrator.GetJobResponseB7Z5github.com/anshul439/go-orchestrator/gen/orchestratorb\x06proto3"

var (
	file_proto_orchestrator_proto_rawDescOnce sync.Once
	file_proto_orchestrator_proto_rawDescData []byte
)

func file_proto_orchestrator_proto_rawDescGZIP() []byte {
	file_proto_orchestrator_proto_rawDescOnce.Do(func() {
		file_proto_orchestrator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_orchestrator_proto_rawDesc), len(file_proto_orchestrator_proto_rawDesc)))
	})
	return file_proto_orchestrator_proto_rawDescData
}

var file_proto_orchestrator_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_orchestrator_proto_goTypes = []any{
	(*SubmitJobRequest)(nil),  // 0: orchestrator.SubmitJobRequest
	(*SubmitJobResponse)(nil), // 1: orchestrator.SubmitJobResponse
	(*GetJobRequest)(nil),     // 2: orchestrator.GetJobRequest
	(*GetJobResponse)(nil),    // 3: orchestrator.GetJobResponse
}
var file_proto_orchestrator_proto_depIdxs = []int32{
	0, // 0: orchestrator.OrchestratorService.SubmitJob:input_type -> orchestrator.SubmitJobRequest
	2, // 1: orchestrator.OrchestratorService.GetJob:input_type -> orchestrator.GetJobRequest
	1, // 2: orchestrator.OrchestratorService.SubmitJob:output_type -> orchestrator.SubmitJobResponse
	3, // 3: orchestrator.OrchestratorService.GetJob:output_type -> orchestrator.GetJobResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_orchestrator_proto_init() }
func file_proto_orchestrator_proto_init() {
	if File_proto_orchestrator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_orchestrator_proto_rawDesc), len(file_proto_orchestrator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_orchestrator_proto_goTypes,
		DependencyIndexes: file_proto_orchestrator_proto_depIdxs,
		MessageInfos:      file_proto_orchestrator_proto_msgTypes,
	}.Build()
	File_proto_orchestrator_proto = out.File
	file_proto_orchestrator_proto_goTypes = nil
	file_proto_orchestrator_proto_depIdxs = nil
}
